# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: Sungyoon Kim
description: >- # this means to ignore newlines until "baseurl:"
  Sungyoon Kim's blog
baseurl: "/bay" # the subpath of the site
url: "https://eliottvincent.github.io" # the base hostname & protocol for the site
og_image: /assets/img/profile-pic.jpg
google_analytics: "UA-121636368-3"

header:
  pages:
    - name: Home
      slug: /
    - name: CV
    - name: Publications
    - name: Projects
    - name: Posts

footer:
  show_powered_by: true
  contact:
    - name: Email
      value: clifter0122@gmail.com
      link: mailto:clifter0122@gmail.com

  follow:
  
    - name: LinkedIn
      link: http://linkedin.com/in/성윤-김-132323248/
    - name: GitHub
      link: http://github.com/laundaryman
    - name: RSS
      link: /feed.xml

# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1
